In [1]:
import csv
import nltk
from nltk import FreqDist
import pandas as pd
import numpy as np


In [2]:
## -- Step 1: tokenizing --
words = []
with open('Tweets2.csv', newline='', encoding="utf8") as csvfile:
	reader = csv.DictReader(csvfile, quoting=csv.QUOTE_ALL)
	for row in reader:
		#print(row['airline_sentiment'], row['text'])
		words = words + (nltk.tokenize.word_tokenize(row["text"].lower()))
print(words)

['@', 'virginamerica', 'what', '@', 'dhepburn', 'said', '.', '@', 'virginamerica', 'plus', 'you', "'ve", 'added', 'commercials', 'to', 'the', 'experience', '...', 'tacky', '.', '@', 'virginamerica', 'i', 'did', "n't", 'today', '...', 'must', 'mean', 'i', 'need', 'to', 'take', 'another', 'trip', '!', '@', 'virginamerica', 'it', "'s", 'really', 'aggressive', 'to', 'blast', 'obnoxious', '``', 'entertainment', "''", 'in', 'your', 'guests', "'", 'faces', '&', 'amp', ';', 'they', 'have', 'little', 'recourse', '@', 'virginamerica', 'and', 'it', "'s", 'a', 'really', 'big', 'bad', 'thing', 'about', 'it', '@', 'virginamerica', 'seriously', 'would', 'pay', '$', '30', 'a', 'flight', 'for', 'seats', 'that', 'did', "n't", 'have', 'this', 'playing', '.', 'it', "'s", 'really', 'the', 'only', 'bad', 'thing', 'about', 'flying', 'va', '@', 'virginamerica', 'yes', ',', 'nearly', 'every', 'time', 'i', 'fly', 'vx', 'this', '“', 'ear', 'worm', 'wo', "n't", 'go', 'away', ':', ')', "''", '@', 'virginamerica', 

In [3]:
len(words)

20790

In [4]:
## -- Step 2: stemming -- 
stemmedWords = []
from nltk.stem import PorterStemmer
pst=PorterStemmer()
for row in words:
	stemmedWords = stemmedWords + [pst.stem(row)]
	

print(stemmedWords)

['@', 'virginamerica', 'what', '@', 'dhepburn', 'said', '.', '@', 'virginamerica', 'plu', 'you', "'ve", 'ad', 'commerci', 'to', 'the', 'experi', '...', 'tacki', '.', '@', 'virginamerica', 'i', 'did', "n't", 'today', '...', 'must', 'mean', 'i', 'need', 'to', 'take', 'anoth', 'trip', '!', '@', 'virginamerica', 'it', "'s", 'realli', 'aggress', 'to', 'blast', 'obnoxi', '``', 'entertain', "''", 'in', 'your', 'guest', "'", 'face', '&', 'amp', ';', 'they', 'have', 'littl', 'recours', '@', 'virginamerica', 'and', 'it', "'s", 'a', 'realli', 'big', 'bad', 'thing', 'about', 'it', '@', 'virginamerica', 'serious', 'would', 'pay', '$', '30', 'a', 'flight', 'for', 'seat', 'that', 'did', "n't", 'have', 'thi', 'play', '.', 'it', "'s", 'realli', 'the', 'onli', 'bad', 'thing', 'about', 'fli', 'va', '@', 'virginamerica', 'ye', ',', 'nearli', 'everi', 'time', 'i', 'fli', 'vx', 'thi', '“', 'ear', 'worm', 'wo', "n't", 'go', 'away', ':', ')', "''", '@', 'virginamerica', 'realli', 'miss', 'a', 'prime', 'opport

In [5]:
len(stemmedWords)

20790

In [6]:
## -- Step 3 A: stopword en-default --
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))
stoppedWord = []
for w in stemmedWords:
    if w not in stopWords:
        stoppedWord.append(w)
print(stoppedWord)

['@', 'virginamerica', '@', 'dhepburn', 'said', '.', '@', 'virginamerica', 'plu', "'ve", 'ad', 'commerci', 'experi', '...', 'tacki', '.', '@', 'virginamerica', "n't", 'today', '...', 'must', 'mean', 'need', 'take', 'anoth', 'trip', '!', '@', 'virginamerica', "'s", 'realli', 'aggress', 'blast', 'obnoxi', '``', 'entertain', "''", 'guest', "'", 'face', '&', 'amp', ';', 'littl', 'recours', '@', 'virginamerica', "'s", 'realli', 'big', 'bad', 'thing', '@', 'virginamerica', 'serious', 'would', 'pay', '$', '30', 'flight', 'seat', "n't", 'thi', 'play', '.', "'s", 'realli', 'onli', 'bad', 'thing', 'fli', 'va', '@', 'virginamerica', 'ye', ',', 'nearli', 'everi', 'time', 'fli', 'vx', 'thi', '“', 'ear', 'worm', 'wo', "n't", 'go', 'away', ':', ')', "''", '@', 'virginamerica', 'realli', 'miss', 'prime', 'opportun', 'men', 'without', 'hat', 'parodi', ',', '.', 'http', ':', '//t.co/mwpg7grezp', '@', 'virginamerica', 'well', ',', "didn't…but", '!', ':', '-d', '@', 'virginamerica', 'wa', 'amaz', ',', 'ar

In [7]:
list_stopword = []
## -- Step 3 B: Stopword additional
#masukkan semua stopwords ke file stopwords.txt
with open('stopwords.txt',encoding ='ISO-8859-1') as stopword:
	for line in stopword:
		list_stopword.append(line.strip())
cleanWords = []
for w in stoppedWord:
	if w not in list_stopword: 
		# jika kata tidak termasuk dlm stop words
		cleanWords.append(w) 
print(cleanWords)

['@', 'virginamerica', '@', 'dhepburn', '.', '@', 'virginamerica', 'plu', "'ve", 'ad', 'commerci', 'experi', '...', 'tacki', '.', '@', 'virginamerica', "n't", '...', 'mean', 'anoth', 'trip', '!', '@', 'virginamerica', "'s", 'realli', 'aggress', 'blast', 'obnoxi', '``', 'entertain', "''", 'guest', "'", '&', 'amp', ';', 'littl', 'recours', '@', 'virginamerica', "'s", 'realli', 'bad', '@', 'virginamerica', 'serious', 'pay', '$', '30', 'flight', 'seat', "n't", 'thi', 'play', '.', "'s", 'realli', 'onli', 'bad', 'fli', 'va', '@', 'virginamerica', 'ye', ',', 'nearli', 'everi', 'time', 'fli', 'vx', 'thi', '“', 'ear', 'worm', 'wo', "n't", ':', ')', "''", '@', 'virginamerica', 'realli', 'miss', 'prime', 'opportun', 'hat', 'parodi', ',', '.', 'http', ':', '//t.co/mwpg7grezp', '@', 'virginamerica', ',', "didn't…but", '!', ':', '-d', '@', 'virginamerica', 'wa', 'amaz', ',', 'arriv', 'hour', 'earli', '.', "'re", '.', '@', 'virginamerica', 'suicid', 'lead', 'caus', 'death', 'teen', '10-24', '@', 'vir

In [8]:
data = pd.read_csv('Tweets2.csv')

In [9]:
data1 = data[['airline_sentiment','text']]

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(smooth_idf=False, sublinear_tf=False, norm=None, analyzer='word',use_idf=True,stop_words=list_stopword)

In [11]:
txt_fitted = tf.fit(data1["text"])

C:\Users\User\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:286: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['available', 'balancing', 'com', 'coverage', 'freely', 'html', 'http', 'lextek', 'list', 'manuals', 'onix', 'size', 'stopword', 'stopwords', 'stopwords1', 'txt', 'www'] not in stop_words.
  sorted(inconsistent))


In [12]:
txt_transformed = txt_fitted.transform(data1["text"])


In [13]:
scores = zip(tf.get_feature_names(),
                 np.asarray(txt_transformed.sum(axis=0)).ravel())
sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
for item in sorted_scores:
        print("{0:10} Score: {1}".format(item[0], item[1]))


united     Score: 887.01181824737
virginamerica Score: 852.5922583998829
flight     Score: 578.8822195973513
co         Score: 372.7679993783572
http       Score: 355.50991238783945
thanks     Score: 228.5396519174873
help       Score: 224.99351052328618
flights    Score: 204.63497204535258
service    Score: 192.73587031788568
customer   Score: 181.51458718082577
bag        Score: 175.3001629253378
cancelled  Score: 168.91879985603467
guys       Score: 168.9161596606029
time       Score: 168.9161596606029
please     Score: 167.906087536663
amp        Score: 165.7088738293607
am         Score: 161.45992834655658
thank      Score: 152.6059891270022
airline    Score: 144.87079467511296
plane      Score: 143.53069634778734
flying     Score: 141.465463671385
seat       Score: 136.54585655329439
check      Score: 135.57707437632112
love       Score: 134.56002782605066
website    Score: 132.07548683830393
sfo        Score: 126.02670707688232
fly        Score: 121.35905125922001
dm         Sco

simple     Score: 14.38676892394113
skiing     Score: 14.38676892394113
solution   Score: 14.38676892394113
somehow    Score: 14.38676892394113
song       Score: 14.38676892394113
sooner     Score: 14.38676892394113
soooo      Score: 14.38676892394113
sorted     Score: 14.38676892394113
space      Score: 14.38676892394113
spoiled    Score: 14.38676892394113
spoke      Score: 14.38676892394113
spread     Score: 14.38676892394113
st         Score: 14.38676892394113
started    Score: 14.38676892394113
steel      Score: 14.38676892394113
step       Score: 14.38676892394113
stolen     Score: 14.38676892394113
stopped    Score: 14.38676892394113
stressed   Score: 14.38676892394113
submitted  Score: 14.38676892394113
supervisor Score: 14.38676892394113
switched   Score: 14.38676892394113
systemwide Score: 14.38676892394113
takeoff    Score: 14.38676892394113
talking    Score: 14.38676892394113
tech       Score: 14.38676892394113
thats      Score: 14.38676892394113
tho        Score: 14.3867689

kickin     Score: 7.88653164253051
killed     Score: 7.88653164253051
kinda      Score: 7.88653164253051
kindle     Score: 7.88653164253051
kits       Score: 7.88653164253051
kitty      Score: 7.88653164253051
kj1iljaebv Score: 7.88653164253051
kmm24999563v99860l0km Score: 7.88653164253051
kooples    Score: 7.88653164253051
kqnrrp86a5 Score: 7.88653164253051
kuala      Score: 7.88653164253051
kudos      Score: 7.88653164253051
ladan      Score: 7.88653164253051
lake       Score: 7.88653164253051
lame       Score: 7.88653164253051
lap        Score: 7.88653164253051
larkc8vc4s Score: 7.88653164253051
las2sfo    Score: 7.88653164253051
latrice    Score: 7.88653164253051
laughed    Score: 7.88653164253051
law        Score: 7.88653164253051
leading    Score: 7.88653164253051
learncustomerservice Score: 7.88653164253051
legitimate Score: 7.88653164253051
letsgohome Score: 7.88653164253051
lfs4pefe6y Score: 7.88653164253051
likingyoulessandless Score: 7.88653164253051
limits     Score: 7.8865

shift      Score: 7.88653164253051
shit       Score: 7.88653164253051
shocking   Score: 7.88653164253051
shoes      Score: 7.88653164253051
short      Score: 7.88653164253051
shot       Score: 7.88653164253051
shower     Score: 7.88653164253051
shown      Score: 7.88653164253051
shrinerack Score: 7.88653164253051
silicon    Score: 7.88653164253051
silly      Score: 7.88653164253051
silverstatus Score: 7.88653164253051
simonroesner Score: 7.88653164253051
sincerely  Score: 7.88653164253051
singer     Score: 7.88653164253051
single     Score: 7.88653164253051
situation  Score: 7.88653164253051
sjc        Score: 7.88653164253051
sked       Score: 7.88653164253051
skies      Score: 7.88653164253051
skift      Score: 7.88653164253051
skis       Score: 7.88653164253051
sllyibe2vq Score: 7.88653164253051
slots      Score: 7.88653164253051
slow       Score: 7.88653164253051
smh        Score: 7.88653164253051
smooth     Score: 7.88653164253051
sna        Score: 7.88653164253051
sneaky     Score

In [14]:
toplabel = []
i = 0
for item in sorted_scores:
    if i < 20:
        toplabel.append(item[0])
        i=i+1

In [15]:
print(toplabel)

['united', 'virginamerica', 'flight', 'co', 'http', 'thanks', 'help', 'flights', 'service', 'customer', 'bag', 'cancelled', 'guys', 'time', 'please', 'amp', 'am', 'thank', 'airline', 'plane']


In [17]:
## -- Step 5: Menghitung bag of word --
index=0;
bag_of_words = np.zeros((1000, 20), dtype=np.int)
label = [];
with open('Tweets2.csv', newline='', encoding="utf8") as csvfile:
	reader = csv.DictReader(csvfile, quoting=csv.QUOTE_ALL)
	for row in reader:
		for w in range(20):
			if toplabel[w] in row["text"]:
				bag_of_words[index][w] = 1;
		label.append(row['airline_sentiment'])
		index = index+1
print(bag_of_words)
#print(label)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
# fieldnames untuk membuat header pada file output. kolom pertama adalah kelas sentimen (positive, negative, neutral), kolom selanjutnya adalah kata dalam var common
fieldnames = np.append(['sentiment'],toplabel)
print(fieldnames)

['sentiment' 'united' 'virginamerica' 'flight' 'co' 'http' 'thanks' 'help'
 'flights' 'service' 'customer' 'bag' 'cancelled' 'guys' 'time' 'please'
 'amp' 'am' 'thank' 'airline' 'plane']


In [20]:
with open('names2.csv', mode='w', newline='') as outputcsvfile:
	writer = csv.writer(outputcsvfile, delimiter=',', quoting=csv.QUOTE_NONE, escapechar='\\')
	writer.writerow(fieldnames)
	for w in range(len(label)):
		wekaData = ([''.join(label[w])])
		for f in range(20):
			wekaData.append(bag_of_words[w][f])
		writer.writerow(wekaData)